language: python
python:
  - 2.7
  - 3.6

env:
  - DJANGO=1.11
  
before_install:
  - # sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get install -y swig
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y tidy libreoffice python3-uno
  - libreoffice '--accept=socket,host=127.0.0.1,port=8100;urp;' &

install:
  - pip install -U setuptools
  - pip install coveralls
#  - pip install Django==$DJANGO
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pip install -r requirements.python3.txt; else pip install -r requirements.txt;  fi
#  - test -e "requirements.$TRAVIS_BRANCH.txt" && ( pip install -r "requirements.$TRAVIS_BRANCH.txt" ) || ( pip install -r requirements.txt )
  - pip install -e .
  - pip freeze
  
script:
  - export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache
  - mkdir $LINO_CACHE_ROOT
  - # if [[ $TRAVIS_BRANCH == 'python3' || $TRAVIS_PYTHON_VERSION == 2.7 ]]; then inv prep test; else exit 0; fi;
  - # inv prep test
  - inv cov --no-html

after_script:
  - coveralls

